### ISSUE TITLE
Can't run the pmp-check-aws-rds.py

### ISSUE THREAD

**Issue by Adonist** [percona/percona-monitoring-plugins#45]
No matter how I try I only get this:

Traceback (most recent call last):
  File "./pmp-check-aws-rds.py", line 361, in <module>
    main()
  File "./pmp-check-aws-rds.py", line 192, in main
    info = rds.get_list()
  File "./pmp-check-aws-rds.py", line 69, in get_list
    except (boto.provider.ProfileNotFoundError, boto.exception.BotoServerError) as msg:
AttributeError: 'module' object has no attribute 'ProfileNotFoundError'

**Comment by toozej** [comment]
I ran into this earlier today too using the python-boto package from the Ubuntu Trusty repo (version 2.20.1-2ubuntu2). I was able to get pmp-check-aws-rds.py to run by removing the python-boto package and installing a much more recent version of boto (version 2.48.0) using pip. Hope this helps!
